name: Basic Github Action pipeline

on:
  push:
    branches: ["main"]

jobs:
  Basics:
    runs-on: [self-hosted, linux]

    steps:
      - name: write into a file
        run: echo "hello from Github action pipeline"
    
      
